language: rust
# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic

addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  - cargo clean
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench --verbose --all
  - cargo doc --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi