[package]
name = "mpst"
version = "0.0.1"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
description = "A library implementing multiparty session types"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
categories = ["concurrency", "mpst", "session"]
exclude = ["/doc/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "^0.3.8"
either = "^1.5.0"
