[package]
name = "mpstthree"
version = "0.0.2"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
categories = ["concurrency", "development-tools::cargo-plugins"]
exclude = [".travis.yml", ".gitignore"]
edition = "2018"

[workspace]

[[bin]]
name = "mpst"
path = "main.rs"

[dependencies]
crossbeam-channel = "0.4.2"
either = "1.5.3"
rand = "0.7"
dot = "0.1.4"
mpst-seq = { path = "mpst_seq" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "simple"
harness = false

[badges]
travis-ci = { repository = "NicolasLagaillardie/mpst_rust_github", branch = "master" }