[package]
name = "mpst"
version = "0.0.1"
authors = ["N <lagaillardie.nicolas@live.fr>"]
description = "A library implementing multiparty session types"
readme = "README.md"
license = "MIT"
repository = "https://github.com/NicolasLagaillardie/mpst.git"
categories = ["concurrency", "mpst"]
exclude = ["/doc/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "^0.3.8"
either = "^1.5.0"
