[package]
name = "mpstthree"
version = "0.0.3"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
keywords = ["multiparty", "session"]
categories = ["concurrency", "development-tools::cargo-plugins"]
exclude = [".travis.yml", ".gitignore"]
edition = "2018"
autotests = false

[workspace]

[[bin]]
name = "mpst"
path = "main.rs"

[[test]]
name = "tests"
path = "tests/main.rs"

[[bench]]
name = "main"
harness = false

[[bench]]
name = "ping_pong"
harness = false

[profile.release]
debug = true

[dependencies]
crossbeam-channel = "0.5.1"
either = "1.6.1"
rand = "0.8.3"
# dot = "0.1.4"
# sesh = "0.1.1"
mpst-seq = { git = "https://github.com/NicolasLagaillardie/mpst-seq", branch = "main"}
# mpst-seq = { path = "../mpst-seq" }
anyhow = "1"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1.5.0", features = ["full"] }
futures = "0.3.14"

[dev-dependencies]
criterion = { version = "0.3.4", features=["html_reports"] }
trybuild = "1.0.42"

[badges]
maintenance = { status = "actively-developed" }