[package]
name = "mpstthree"
version = "0.0.1-b"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
categories = ["concurrency"]
exclude = ["/doc/*"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "^0.3.8"
either = "^1.5.0"
