[package]
name = "mpstthree"
version = "0.0.3"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
keywords = ["multiparty", "session"]
categories = ["concurrency", "development-tools::cargo-plugins"]
exclude = [".travis.yml", ".gitignore"]
edition = "2018"

[workspace]

[[bin]]
name = "mpst"
path = "main.rs"

[profile.release]
debug = true

[dependencies]
crossbeam-channel = "0.5.0"
either = "1.6.1"
rand = "0.7.3"
# dot = "0.1.4"
mpst-seq = { git = "https://github.com/NicolasLagaillardie/mpst-seq", branch = "main"}
# mpst-seq = {path = "../mpst-seq"}

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "main"
harness = false

[badges]
maintenance = { status = "actively-developed" }