[package]
name = "mpstthree"
version = "0.0.1"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
categories = ["concurrency"]
exclude = ["/doc/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "^0.3.8"
either = "^1.5.0"
