[package]
name = "mpstthree"
version = "0.0.1-d"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "A library implementing Multiparty Session Types for 3 participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
categories = ["concurrency"]
exclude = [".travis.yml", ".gitignore"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "^0.3.8"
either = "^1.5.0"
rand = "0.7"

[badges]
travis-ci = { repository = "NicolasLagaillardie/mpst_rust_github", branch = "master" }