[package]
name = "mpstthree"
version = "0.0.10"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
edition = "2018"
description = "A library implementing Multiparty Session Types for 2 or more participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
license = "MIT"
keywords = ["multiparty", "session"]
categories = ["concurrency", "development-tools::cargo-plugins"]
exclude = [".travis.yml", "codecov.yml", ".gitignore", "mpst_seq/", ".github/", ".cargo_vcs_info.json", "scripts/", "example/", "rustfmt_2.toml"]
autotests = false

[workspace]
exclude = ["mpst_seq/"]

[[bin]]
name = "mpst"
path = "main.rs"

[[test]]
name = "tests"
path = "tests/main.rs"

[[bench]]
name = "main"
harness = false

[[bench]]
name = "ping_pong"
harness = false

[profile.release]
debug = true

[dependencies]
mpst-seq = { path = "mpst_seq", version = "0.0.8" }
# mpst-seq = "0.0.8"
crossbeam-channel = "0.5.1"
either = "1.6.1"
rand = "0.8.4"
hyper = { version = "0.14.10", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1.8.1", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.3.4", features = ["html_reports"] }
trybuild = "1.0.42"
ntest = "0.7.3"

[badges]
maintenance = { status = "actively-developed" }
