[package]
name = "mpstthree"
version = "0.0.10"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
edition = "2018"
description = "A library implementing Multiparty Session Types for 2 or more participants"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
license = "MIT"
keywords = ["multiparty", "session"]
categories = ["concurrency", "development-tools::cargo-plugins"]
exclude = [
    ".travis.yml",
    "codecov.yml",
    ".gitignore",
    "mpst_seq/",
    ".github/",
    ".cargo_vcs_info.json",
    "scripts/",
    "example/",
    "rustfmt_2.toml",
]
autotests = false

###################################

[workspace]
exclude = ["mpst_seq/"]

###################################

[[bin]]
name = "mpst"
path = "main.rs"

###################################

[[test]]
name = "main-tests"
path = "tests/main.rs"
required-features = ["full", "rand"]

[[test]]
name = "kmc-tests"
path = "tests/kmc.rs"
required-features = ["full", "rand"]

###################################

[[bench]]
name = "main"
harness = false
required-features = ["macros", "rand"]

[[bench]]
name = "ping_pong"
harness = false
required-features = ["macros", "rand"]

###################################

[[example]]
name = "actyx_os_api"
required-features = ["macros", "rand"]

[[example]]
name = "actyx_os_logging"
required-features = ["macros", "rand"]

[[example]]
name = "distributed_calc"
required-features = ["macros", "rand"]

[[example]]
name = "dns_fowler"
required-features = ["macros", "rand"]

[[example]]
name = "dns_imai"
required-features = ["macros", "rand"]

[[example]]
name = "fib"
required-features = ["macros", "rand"]

[[example]]
name = "o_auth"
required-features = ["macros", "rand"]

[[example]]
name = "o_auth_2"
required-features = ["macros", "transport", "rand"]

[[example]]
name = "online_wallet"
required-features = ["macros", "rand"]

[[example]]
name = "simple_voting"
required-features = ["macros", "rand"]

[[example]]
name = "smtp"
required-features = ["macros", "rand"]

[[example]]
name = "three_buyers"
required-features = ["macros", "rand"]

[[example]]
name = "travel_three"
required-features = ["macros", "rand"]

[[example]]
name = "video_stream"
required-features = ["macros", "rand"]

###################################

[profile.release]
debug = true

###################################

[dependencies]
mpst-seq = { path = "mpst_seq", version = "0.0.8" }
# mpst-seq = "0.0.8"
crossbeam-channel = "0.5.1"
either = "1.6.1"
rand = { version = "0.8.4", optional = true }
hyper = { version = "0.14.12", features = ["full"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
tokio = { version = "1.10.1", features = ["full"], optional = true }
regex = { version = "1.5.4", optional = true }
petgraph = { version = "0.6.0", optional = true }

###################################

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
trybuild = "1.0.45"
ntest = "0.7.3"

###################################

[features]
default = ["binary", "role", "meshedchannels", "functionmpst"]
binary = []
functionmpst = []
meshedchannels = []
role = []
macros = ["default"]
checking = ["default", "regex", "petgraph"]
baking = ["default"]
transport = ["default", "hyper", "hyper-tls", "tokio"]
full = ["checking", "macros", "baking", "transport"]

###################################

[badges]
maintenance = { status = "actively-developed" }
