codecov:
  require_ci_to_pass: yes

ignore:
  - "mpst_seq/"
  - "mpst_seq_proc/"
  - "benches/"
  - "examples/"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no # Might be changed

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: yes
