# array_width = 60
# attr_fn_like_width = 70
binop_separator = "Front" # "Front", "Back"
# blank_lines_lower_bound = 1
# blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine" # "AlwaysNextLine", "PreferSameLine", "SameLineWhere"
# chain_width = 60
combine_control_expr = false # true, false
comment_width = 100
# condense_wildcard_suffixes = false # "true", "false"
control_brace_style = "AlwaysSameLine" # "AlwaysNextLine", "AlwaysSameLine", "ClosingNextLine"
# edition = "2018"
# empty_item_single_line = true # true, false
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false # true, false
# error_on_unformatted = false # true, false
# fn_params_layout = "Tall" # "Compressed", "Tall", "Vertical"
# fn_call_width = 60
force_multiline_blocks = true # true, false
format_code_in_doc_comments = true # true, false
format_macro_matchers = true # true, false
format_macro_bodies = true # true, false
format_strings = false # true, false
max_width = 100
wrap_comments = true