[package]
name = "mpst-seq"
version = "0.0.7"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
description = "A library with macro for mpstthree"
edition = "2018"
readme = "README.md"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github/tree/master/mpst_seq/"
license = "MIT"
exclude = ["mpst_seq_proc/"]
autotests = false

[workspace]
exclude = ["mpst_seq_proc/"]

[dev-dependencies]
trybuild = "1.0.42"

[dependencies]
proc-macro-hack = "0.5.19"
mpst-seq-proc = { path = "mpst_seq_proc", version = "0.0.7" }
# mpst-seq-proc = "0.0.7"
