[package]
name = "mpst_seq"
version = "0.0.1"
authors = ["NicolasLagaillardie <lagaillardie.nicolas@live.fr>"]
license = "MIT"
description = "Lib for mpst_rust to manage any number of participants"
edition = "2018"

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = "1.0"

[dependencies]
proc-macro-hack = "0.5.18"
crossbeam-channel = "0.4.2"
either = "1.5.3"
mpst-seq-proc = { path = "mpst-seq-proc/" }