[package]
name = "mpst-seq"
version = "0.0.1"
edition = "2018"

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = "1.0"

[dependencies]
proc-macro-hack = "0.5.18"
mpst-seq-proc = { path = "mpst-seq-proc/" }
