[package]
name = "mpst-seq"
version = "0.1.17"
authors = ["XXX"]
description = "A library with macro for mpstthree"
edition = "2018"
readme = "README.md"
homepage = "XXX"
repository = "XXX"
license = "MIT OR Apache-2.0"
autotests = false
include = [
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
proc-macro-hack = "0.5"
mpst-seq-proc = { path = "../mpst_seq_proc" }
# mpst-seq-proc = "0.1"
