[package]
name = "mpstthree"
version = "0.1.17"
authors = ["NicolasLagaillardie <nicolas.lagaillardie@tutanota.com>"]
edition = "2021"
rust-version = "1.77"
description = "A library implementing Multiparty Session Types for 2 or more participants"
readme = "README.md"
homepage = "https://github.com/NicolasLagaillardie/mpst_rust_github"
repository = "https://github.com/NicolasLagaillardie/mpst_rust_github"
license = "MIT OR Apache-2.0"
keywords = ["multiparty", "session", "affine", "multicrusty", "timed"]
documentation = "https://docs.rs/mpstthree"
categories = ["concurrency"]
# include = [
#     "/benches/**",
#     "/build.rs",
#     "/Cargo.toml",
#     "/LICENSE-APACHE",
#     "/LICENSE-MIT",
#     "/README.md",
#     "/src/**",
#     "/tests/**",
#     "/examples/**",
#     "main.rs",
# ]
exclude = [
    ".vscode/",
    ".travis.yml",
    "codecov.yml",
    ".gitignore",
    ".github/",
    ".cargo_vcs_info.json",
    "scripts/",
    "example/",
    "outputs/",
    "cfsm/",
    "compile_time/",
    "graphs_bench/",
    "rustfmt_0.toml",
    "notes.txt",
    "result.rs",
    "results/",
    "save/",
    "expand/",
    "target/",
]
autotests = false
autobenches = false

################################### Workspace

[workspace]
members = ["mpst_seq_proc"]

################################### Lib

[lib]
bench = false

################################### Badges

[badges]
maintenance = { status = "actively-developed" }

################################### Bin

[[bin]]
name = "mpst"
path = "main.rs"
bench = false

################################### Tests

[[test]]
name = "checking"
path = "tests/checking.rs"
required-features = ["macros_multiple", "checking"]

[[test]]
name = "basics"
path = "tests/basics.rs"
required-features = ["checking"]

[[test]]
name = "binary"
path = "tests/binary.rs"
required-features = ["default"]

[[test]]
name = "cancel"
path = "tests/cancel.rs"
required-features = ["baking"]

[[test]]
name = "macros_multiple"
path = "tests/macros_multiple.rs"
required-features = ["macros_multiple"]

[[test]]
name = "macros_simple"
path = "tests/macros_simple.rs"
required-features = ["macros_simple"]

[[test]]
name = "baking"
path = "tests/baking.rs"
required-features = ["baking", "checking"]

[[test]]
name = "extra"
path = "tests/extra.rs"
required-features = ["baking"]

[[test]]
name = "interleaved"
path = "tests/interleaved.rs"
required-features = ["baking_interleaved"]

[[test]]
name = "binary_timed"
path = "tests/binary_timed.rs"
required-features = ["binary_timed"]

[[test]]
name = "baking_timed"
path = "tests/baking_timed.rs"
required-features = ["baking_timed"]

[[test]]
name = "baking_message"
path = "tests/baking_message.rs"
required-features = ["baking", "checking"]

[[test]]
name = "main"
path = "tests/main.rs"
required-features = []

################################### Benches

################################### Ping-Pong

######### Ping-Pong start
######### Ping-Pong end

################## Examples

######### Timed

[[bench]]
name = "example_calculator_timed"
harness = false
path = "benches/examples/timed/calculator.rs"
required-features = ["full"]

[[bench]]
name = "example_fib_timed"
harness = false
path = "benches/examples/timed/fib.rs"
required-features = ["full"]

[[bench]]
name = "example_o_auth_timed"
harness = false
path = "benches/examples/timed/o_auth.rs"
required-features = ["full"]

[[bench]]
name = "example_online_wallet_timed"
harness = false
path = "benches/examples/timed/online_wallet.rs"
required-features = ["full"]

[[bench]]
name = "example_simple_voting_timed"
harness = false
path = "benches/examples/timed/simple_voting.rs"
required-features = ["full"]

[[bench]]
name = "example_smtp_timed"
harness = false
path = "benches/examples/timed/smtp.rs"
required-features = ["full"]

[[bench]]
name = "example_three_buyers_timed"
harness = false
path = "benches/examples/timed/three_buyers.rs"
required-features = ["full"]

[[bench]]
name = "example_travel_agency_timed"
harness = false
path = "benches/examples/timed/travel_agency.rs"
required-features = ["full"]

[[bench]]
name = "example_servo_timed"
harness = false
path = "benches/examples/timed/servo.rs"
required-features = ["full"]

[[bench]]
name = "example_remote_data_timed"
harness = false
path = "benches/examples/timed/remote_data.rs"
required-features = ["full"]

[[bench]]
name = "example_http_timed"
harness = false
path = "benches/examples/timed/http.rs"
required-features = ["full"]

[[bench]]
name = "example_circuit_breaker_timed"
harness = false
path = "benches/examples/timed/circuit_breaker.rs"
required-features = ["full"]

[[bench]]
name = "example_logging_timed"
harness = false
path = "benches/examples/timed/logging.rs"
required-features = ["full"]

[[bench]]
name = "example_video_stream_timed"
harness = false
path = "benches/examples/timed/video_stream.rs"
required-features = ["full"]

[[bench]]
name = "example_distributed_calculators_timed"
harness = false
path = "benches/examples/timed/distributed_calculators.rs"
required-features = ["full"]

[[bench]]
name = "example_gravity_android_atmp"
harness = false
path = "benches/examples/rate_based_atmp/gravity_android.rs"
required-features = ["full"]

[[bench]]
name = "example_pinetime_heart_rate_atmp"
harness = false
path = "benches/examples/rate_based_atmp/pinetime_heart_rate.rs"
required-features = ["full"]

[[bench]]
name = "example_proximity_based_car_key_atmp"
harness = false
path = "benches/examples/rate_based_atmp/proximity_based_car_key.rs"
required-features = ["full"]

################## Ring

######### Baking Cancel

[[bench]]
name = "ring_two_mpst_timed_baking_cancel"
harness = false
path = "benches/ring/timed_baking_cancel/ring_two.rs"
required-features = ["full"]

[[bench]]
name = "ring_three_mpst_timed_baking_cancel"
harness = false
path = "benches/ring/timed_baking_cancel/ring_three.rs"
required-features = ["full"]

[[bench]]
name = "ring_four_mpst_timed_baking_cancel"
harness = false
path = "benches/ring/timed_baking_cancel/ring_four.rs"
required-features = ["full"]

################## Mesh

######### Baking Cancel

[[bench]]
name = "mesh_two_mpst_timed_baking_cancel"
harness = false
path = "benches/mesh/timed_baking_cancel/mesh_two.rs"
required-features = ["full"]

[[bench]]
name = "mesh_three_mpst_timed_baking_cancel"
harness = false
path = "benches/mesh/timed_baking_cancel/mesh_three.rs"
required-features = ["full"]

[[bench]]
name = "mesh_four_mpst_timed_baking_cancel"
harness = false
path = "benches/mesh/timed_baking_cancel/mesh_four.rs"
required-features = ["full"]

################################### Examples

######### Timed

[[example]]
name = "fib_timed"
path = "examples/timed/fib.rs"
required-features = ["baking_timed"]

[[example]]
name = "servo_timed"
path = "examples/timed/servo.rs"
required-features = ["baking_timed"]

[[example]]
name = "servo_8257_async_failing_timed"
path = "examples/timed/servo_8257_async_failing.rs"
required-features = ["baking_timed"]

[[example]]
name = "servo_8257_async_working_timed"
path = "examples/timed/servo_8257_async_working.rs"
required-features = ["baking_timed"]

[[example]]
name = "servo_8257_async_fixed_timed"
path = "examples/timed/servo_8257_async_fixed.rs"
required-features = ["baking_timed"]

[[example]]
name = "simple_voting_timed"
path = "examples/timed/simple_voting.rs"
required-features = ["baking_timed"]

[[example]]
name = "calculator_timed"
path = "examples/timed/calculator.rs"
required-features = ["baking_timed"]

[[example]]
name = "o_auth_timed"
path = "examples/timed/o_auth.rs"
required-features = ["baking_timed"]

[[example]]
name = "online_wallet_timed"
path = "examples/timed/online_wallet.rs"
required-features = ["baking_timed"]

[[example]]
name = "smtp_timed"
path = "examples/timed/smtp.rs"
required-features = ["baking_timed"]

[[example]]
name = "three_buyers_timed"
path = "examples/timed/three_buyers.rs"
required-features = ["baking_timed"]

[[example]]
name = "travel_agency_timed"
path = "examples/timed/travel_agency.rs"
required-features = ["baking_timed"]

[[example]]
name = "remote_data_timed"
path = "examples/timed/remote_data.rs"
required-features = ["baking_timed"]

[[example]]
name = "http_timed"
path = "examples/timed/http.rs"
required-features = ["baking_timed"]

[[example]]
name = "non_feasible_timed"
path = "examples/timed/non_feasible.rs"
required-features = ["baking_timed"]

[[example]]
name = "circuit_breaker_timed"
path = "examples/timed/circuit_breaker.rs"
required-features = ["baking_timed"]

[[example]]
name = "logging_timed"
path = "examples/timed/logging.rs"
required-features = ["baking_timed"]

[[example]]
name = "video_stream_timed"
path = "examples/timed/video_stream.rs"
required-features = ["baking_timed"]

[[example]]
name = "distributed_calculators_timed"
path = "examples/timed/distributed_calculators.rs"
required-features = ["baking_timed"]

[[example]]
name = "gravity_android_timed"
path = "examples/rate_based_atmp/gravity_android.rs"
required-features = ["baking_timed"]

[[example]]
name = "pinetime_heart_rate_timed"
path = "examples/rate_based_atmp/pinetime_heart_rate.rs"
required-features = ["baking_timed"]

[[example]]
name = "proximity_based_car_key_timed"
path = "examples/rate_based_atmp/proximity_based_car_key.rs"
required-features = ["baking_timed"]

################################### Mesh examples

################## Timed

[[example]]
name = "mesh_two_baking_atmp"
path = "examples/mesh/mesh_two_baking_atmp.rs"
required-features = ["baking_timed"]

[[example]]
name = "mesh_three_baking_atmp"
path = "examples/mesh/mesh_three_baking_atmp.rs"
required-features = ["baking_timed"]

[[example]]
name = "mesh_four_baking_atmp"
path = "examples/mesh/mesh_four_baking_atmp.rs"
required-features = ["baking_timed"]

################################### Ring examples

################## Timed

[[example]]
name = "ring_two_baking_atmp"
path = "examples/ring/ring_two_baking_atmp.rs"
required-features = ["baking_timed"]

[[example]]
name = "ring_three_baking_atmp"
path = "examples/ring/ring_three_baking_atmp.rs"
required-features = ["baking_timed"]

[[example]]
name = "ring_four_baking_atmp"
path = "examples/ring/ring_four_baking_atmp.rs"
required-features = ["baking_timed"]

################################### Timed artifact examples

[[example]]
name = "timed_my_basic"
path = "examples/artifact_timed/my_basic.rs"
required-features = ["baking_timed"]

[[example]]
name = "timed_basic"
path = "examples/artifact_timed/basic.rs"
required-features = ["baking_timed"]

################################### Readme example

[[example]]
name = "readme"
path = "examples/readme_example.rs"
required-features = ["mpst"]

################################### Profil

[profile.release]
debug = true

################################### Dependencies

[dependencies]
mpst-seq-proc = { path = "mpst_seq_proc" }
# mpst-seq-proc = "0.1"
crossbeam-channel = "0.5.8"
either = "1.9.0"
# For HTTP
# hyper = { version = "1.2.0", features = ["full"], optional = true }
# hyper-tls = { version = "0.6.0", optional = true }
# hyper-util = { version = "0.1.3", features = ["full"] }
# http-body-util = "0.1"
# tokio = { version = "1.33.0", features = ["full"], optional = true }
# For kMC
regex = { version = "1.10.0", optional = true }
petgraph = { version = "0.6.4", optional = true }
# Protobuf libraries
protobuf = { version = "3.3.0", features = ["with-bytes"] }
protobuf-codegen = "3.3.0"
protoc-bin-vendored = "3.0.0"

################################### Dev-dependencies for tests/benches

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
trybuild = "1.0.85"
ntest = "0.9.0"
rand = "0.8.5"

################################### Features

[features]
default = []
mpst = ["default"]
binary_timed = ["default"]
macros_simple = ["mpst"]
macros_multiple = ["mpst", "macros_simple"]
checking = ["mpst", "regex", "petgraph"]
baking = ["mpst", "macros_multiple"]
interleaved = ["baking"] # For interleaved sessions
baking_timed = ["binary_timed", "mpst"]
baking_interleaved = ["baking", "interleaved"]
baking_checking = ["baking", "checking"]
baking_timed_interleaved = ["baking_timed", "interleaved"]
transport_tcp = ["default"]
transport_udp = ["default"]
# transport_http = ["default", "hyper", "hyper-tls", "tokio"]
# transport = ["transport_tcp", "transport_udp", "transport_http"]
transport = ["transport_tcp", "transport_udp"]
transport_macros_multiple = [
    "macros_multiple",
    "transport",
] # For test compile examples
protobuf_feature = []
affine_timed = ["baking", "baking_timed"]
full_without_checking = ["baking", "transport", "interleaved"]
full = ["baking_checking", "transport", "baking_timed", "interleaved"]

################################### Doc handling for all-features

# docs.rs-specific configuration
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

################################### Rust playground features

[package.metadata.playground]
features = ["full", "interleaved"]
