[package]
name = "mpst-seq-proc"
version = "0.1.14"
authors = ["XXX"]
description = "A library with macro for mpstthree"
edition = "2021"
rust-version = "1.77"
readme = "README.md"
homepage = "XXX"
repository = "XXX"
license = "MIT OR Apache-2.0"
autotests = false
include = [
    "Cargo.toml",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "README.md",
    "src/",
]

[lib]
proc-macro = true

[badges]
maintenance = { status = "actively-developed" }

[dev-dependencies]
trybuild = "1.0"

[dependencies]
syn = { version = "2.0.38", features = ["extra-traits", "full", "parsing"] }
quote = "1.0.33"
proc-macro2 = "1.0.69"
itertools = "0.12.1"
