[package]
name = "mpanon"
version = "0.1.17"
authors = ["XXX"]
edition = "2021"
rust-version = "1.77.2"
description = "A library implementing Multiparty Session Types for 2 or more participants"
readme = "README.md"
homepage = "XXX"
repository = "XXX"
license = "MIT OR Apache-2.0"
keywords = ["multiparty", "session", "affine", "timed"]
documentation = "https://docs.rs/mpanon"
categories = ["concurrency"]
# include = [
#     "/benches/**",
#     "/build.rs",
#     "/Cargo.toml",
#     "/LICENSE-APACHE",
#     "/LICENSE-MIT",
#     "/README.md",
#     "/src/**",
#     "/tests/**",
#     "/examples/**",
#     "main.rs",
# ]
exclude = [
    ".vscode/",
    ".travis.yml",
    "codecov.yml",
    ".gitignore",
    ".github/",
    ".cargo_vcs_info.json",
    "scripts/",
    "example/",
    "outputs/",
    "cfsm/",
    "compile_time/",
    "graphs_bench/",
    "rustfmt_0.toml",
    "notes.txt",
    "result.rs",
    "results/",
    "save/",
    "expand/",
    "target/",
]
autotests = false
autobenches = false

################################### Workspace

[workspace]
members = ["mpst_seq_proc"]

################################### Lib

[lib]
bench = false

################################### Badges

[badges]
maintenance = { status = "actively-developed" }

################################### Bin

[[bin]]
name = "mpst"
path = "main.rs"
bench = false

################################### Tests

[[test]]
name = "checking"
path = "tests/checking.rs"
required-features = ["macros_multiple", "checking"]

[[test]]
name = "basics"
path = "tests/basics.rs"
required-features = ["checking"]

[[test]]
name = "binary"
path = "tests/binary.rs"
required-features = ["default"]

[[test]]
name = "cancel"
path = "tests/cancel.rs"
required-features = ["baking"]

[[test]]
name = "macros_multiple"
path = "tests/macros_multiple.rs"
required-features = ["macros_multiple"]

[[test]]
name = "macros_simple"
path = "tests/macros_simple.rs"
required-features = ["macros_simple"]

[[test]]
name = "baking"
path = "tests/baking.rs"
required-features = ["baking", "checking"]

[[test]]
name = "extra"
path = "tests/extra.rs"
required-features = ["baking"]

[[test]]
name = "interleaved"
path = "tests/interleaved.rs"
required-features = ["baking_interleaved"]

[[test]]
name = "binary_timed"
path = "tests/binary_timed.rs"
required-features = ["binary_timed"]

[[test]]
name = "baking_timed"
path = "tests/baking_timed.rs"
required-features = ["baking_timed"]

[[test]]
name = "baking_message"
path = "tests/baking_message.rs"
required-features = ["baking", "checking"]

[[test]]
name = "main"
path = "tests/main.rs"
required-features = []

################################### Artifact examples

[[example]]
name = "my_basic"
path = "examples/artifact/my_basic.rs"
required-features = ["baking"]

[[example]]
name = "basic"
path = "examples/artifact/basic.rs"
required-features = ["baking"]

################################### Timed artifact examples

[[example]]
name = "timed_my_basic"
path = "examples/artifact_timed/my_basic.rs"
required-features = ["baking_timed"]

[[example]]
name = "timed_basic"
path = "examples/artifact_timed/basic.rs"
required-features = ["baking_timed"]

################################### Examples

[[example]]
name = "distributed_calculators_crossbeam"
path = "examples/crossbeam/distributed_calculators.rs"
required-features = ["default"]

[[example]]
name = "distributed_calculators_binary"
path = "examples/binary/distributed_calculators.rs"
required-features = ["default"]

[[example]]
name = "distributed_calculators_mpst"
path = "examples/mpst/distributed_calculators.rs"
required-features = ["baking"]

[[example]]
name = "distributed_calculators_ampst"
path = "examples/ampst/distributed_calculators.rs"
required-features = ["baking"]

[[example]]
name = "distributed_calculators_timed"
path = "examples/timed/distributed_calculators.rs"
required-features = ["baking_timed"]

################################### Benches examples

[[bench]]
name = "example_distributed_calculators_crossbeam"
harness = false
path = "benches/examples/crossbeam/distributed_calculators.rs"
required-features = ["full"]

[[bench]]
name = "example_distributed_calculators_binary"
harness = false
path = "benches/examples/binary/distributed_calculators.rs"
required-features = ["full"]

[[bench]]
name = "example_distributed_calculators_mpst"
harness = false
path = "benches/examples/mpst/distributed_calculators.rs"
required-features = ["full"]

[[bench]]
name = "example_distributed_calculators_ampst"
harness = false
path = "benches/examples/ampst/distributed_calculators.rs"
required-features = ["full"]

[[bench]]
name = "example_distributed_calculators_timed"
harness = false
path = "benches/examples/timed/distributed_calculators.rs"
required-features = ["full"]

################################### Rate-based examples

[[example]]
name = "rate_based_car_key"
path = "examples/rate_based/proximity_based_car_key.rs"
required-features = ["baking_timed"]

[[example]]
name = "rate_based_pine_time"
path = "examples/rate_based/pinetime_heart_rate.rs"
required-features = ["baking_timed"]

[[example]]
name = "rate_based_gravity_android"
path = "examples/rate_based/gravity_android.rs"
required-features = ["baking_timed"]

################################### Readme example

[[example]]
name = "readme"
path = "examples/readme_example.rs"
required-features = ["mpst"]

################################### Ping-Pong

######### Ping-Pong start
######### Ping-Pong end

################################### Profil

[profile.release]
debug = true

################################### Dependencies

[dependencies]
mpst-seq-proc = { path = "mpst_seq_proc" }
# mpst-seq-proc = "0.1"
crossbeam-channel = "0.5.8"
either = "1.9.0"
# Extension libraries
hyper = { version = "0.14.27", features = ["full"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
tokio = { version = "1.33.0", features = ["full"], optional = true }
# For kMC
regex = { version = "1.10.0", optional = true }
petgraph = { version = "0.6.4", optional = true }
# Protobuf libraries
protobuf = { version = "3.3.0", features = ["with-bytes"] }
protobuf-codegen = "3.3.0"
protoc-bin-vendored = "3.0.0"

################################### Dev-dependencies for tests/benches

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
trybuild = "1.0.85"
ntest = "0.9.0"
rand = "0.8.5"

################################### Features

[features]
default = []
mpst = ["default"]
binary_timed = ["default"]
macros_simple = ["mpst"]
macros_multiple = ["mpst", "macros_simple"]
checking = ["mpst", "regex", "petgraph"]
baking = ["mpst", "macros_multiple"]
interleaved = ["baking"] # For interleaved sessions
baking_timed = ["binary_timed", "mpst"]
baking_interleaved = ["baking", "interleaved"]
baking_checking = ["baking", "checking"]
baking_timed_interleaved = ["baking_timed", "interleaved"]
transport_tcp = ["default"]
transport_udp = ["default"]
# transport_http = ["default", "hyper", "hyper-tls", "tokio"]
# transport = ["transport_tcp", "transport_udp", "transport_http"]
transport = ["transport_tcp", "transport_udp"]
transport_macros_multiple = [
    "macros_multiple",
    "transport",
] # For test compile examples
protobuf_feature = []
affine_timed = ["baking", "baking_timed"]
full_without_checking = ["baking", "transport", "interleaved"]
full = ["baking_checking", "transport", "baking_timed", "interleaved"]

################################### Doc handling for all-features

# docs.rs-specific configuration
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

################################### Rust playground features

[package.metadata.playground]
features = ["full", "interleaved"]
