[package]
name = "mpstthree"
version = "0.1.16"
authors = ["XXX"]
edition = "2018"
description = "A library implementing Multiparty Session Types for 2 or more participants"
readme = "README.md"
homepage = "XXX"
repository = "XXX"
license = "MIT OR Apache-2.0"
keywords = ["multiparty", "session", "affine", "multicrusty"]
documentation = "https://docs.rs/mpstthree"
categories = ["concurrency"]
include = [
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
    "/tests/**",
    "/examples/**",
    "main.rs",
]
exclude = [
    ".travis.yml",
    "codecov.yml",
    ".gitignore",
    ".github/",
    ".cargo_vcs_info.json",
    "scripts/",
    "example/",
    "outputs/",
    "cfsm/",
    "compile_time/",
    "graphs_bench/",
    "rustfmt_2.toml",
    "notes.txt",
    "result.rs",
]
autotests = false
autobenches = false

################################### Workspace

[workspace]
members = ["mpst_seq", "mpst_seq_proc"]

################################### Lib

[lib]
bench = false

################################### Bin

[[bin]]
name = "mpst"
path = "main.rs"
bench = false

################################### Tests

[[test]]
name = "checking"
path = "tests/checking.rs"
required-features = ["macros_multiple", "checking"]

[[test]]
name = "basics"
path = "tests/basics.rs"
required-features = ["checking"]

[[test]]
name = "binary"
path = "tests/binary.rs"
required-features = ["binary"]

[[test]]
name = "cancel"
path = "tests/cancel.rs"
required-features = ["baking"]

[[test]]
name = "macros_multiple"
path = "tests/macros_multiple.rs"
required-features = ["macros_multiple"]

[[test]]
name = "macros_simple"
path = "tests/macros_simple.rs"
required-features = ["macros_simple"]

[[test]]
name = "transport_udp"
path = "tests/transport_udp.rs"
required-features = ["transport_udp"]

[[test]]
name = "transport_tcp"
path = "tests/transport_tcp.rs"
required-features = ["transport_tcp"]

[[test]]
name = "transport_http"
path = "tests/transport_http.rs"
required-features = ["transport_http", "macros_multiple"]

[[test]]
name = "baking"
path = "tests/baking.rs"
required-features = ["baking", "checking"]

[[test]]
name = "extra"
path = "tests/extra.rs"
required-features = ["baking"]

[[test]]
name = "interleaved"
path = "tests/interleaved.rs"
required-features = ["baking_interleaved"]

[[test]]
name = "main"
path = "tests/main.rs"
required-features = []

################################### Benches

[[bench]]
name = "main"
harness = false
required-features = ["baking"]

[[bench]]
name = "main_interleaved"
harness = false
required-features = ["baking_interleaved"]

[[bench]]
name = "mesh"
harness = false
path = "benches/mesh_full.rs"
required-features = ["baking"]

[[bench]]
name = "ring"
harness = false
path = "benches/ring_full.rs"
required-features = ["baking"]

[[bench]]
name = "ping_pong"
harness = false
required-features = ["baking"]

################################### Basic examples

[[example]]
name = "circuit_breaker"
required-features = ["macros_multiple"]

[[example]]
name = "logging"
required-features = ["macros_multiple"]

[[example]]
name = "circuit_breaker_baking"
required-features = ["baking"]

[[example]]
name = "logging_baking"
required-features = ["baking"]

[[example]]
name = "circuit_breaker_solo"
path = "examples/interleaved/circuit_breaker_solo.rs"
required-features = ["baking_interleaved"]

[[example]]
name = "logging_solo"
path = "examples/interleaved/logging_solo.rs"
required-features = ["baking_interleaved"]

[[example]]
name = "circuit_breaker_logging_interleaved"
path = "examples/interleaved/circuit_breaker_logging_interleaved.rs"
required-features = ["baking_interleaved"]

[[example]]
name = "distributed_calc"
required-features = ["macros_multiple"]

[[example]]
name = "dns_fowler"
required-features = ["baking"]

[[example]]
name = "dns_fowler_checking"
required-features = ["baking_checking"]

[[example]]
name = "dns_imai"
required-features = ["macros_multiple"]

[[example]]
name = "fib"
required-features = ["macros_multiple"]

[[example]]
name = "o_auth"
required-features = ["baking"]

[[example]]
name = "o_auth_checking"
required-features = ["baking_checking"]

[[example]]
name = "o_auth_transport"
required-features = ["transport_macros_multiple"]

[[example]]
name = "online_wallet"
required-features = ["macros_multiple"]

[[example]]
name = "simple_voting"
required-features = ["macros_multiple"]

[[example]]
name = "smtp"
required-features = ["macros_multiple"]

[[example]]
name = "three_buyers"
required-features = ["macros_multiple"]

[[example]]
name = "travel_three"
required-features = ["macros_multiple"]

[[example]]
name = "video_stream_basic"
required-features = ["macros_simple"]

[[example]]
name = "video_stream"
required-features = ["baking_checking"]

[[example]]
name = "adder"
required-features = ["baking_checking"]

[[example]]
name = "basic"
required-features = ["baking_checking"]

################################### Mesh examples

[[example]]
name = "mesh_two_crossbeam"
path = "examples/mesh/mesh_two_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_two_mpst"
path = "examples/mesh/mesh_two_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_two_binary"
path = "examples/mesh/mesh_two_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_two_baking"
path = "examples/mesh/mesh_two_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_three_crossbeam"
path = "examples/mesh/mesh_three_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_three_mpst"
path = "examples/mesh/mesh_three_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_three_binary"
path = "examples/mesh/mesh_three_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_three_baking"
path = "examples/mesh/mesh_three_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_four_crossbeam"
path = "examples/mesh/mesh_four_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_four_mpst"
path = "examples/mesh/mesh_four_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_four_binary"
path = "examples/mesh/mesh_four_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_four_baking"
path = "examples/mesh/mesh_four_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_five_crossbeam"
path = "examples/mesh/mesh_five_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_five_mpst"
path = "examples/mesh/mesh_five_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_five_binary"
path = "examples/mesh/mesh_five_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_five_baking"
path = "examples/mesh/mesh_five_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_six_crossbeam"
path = "examples/mesh/mesh_six_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_six_mpst"
path = "examples/mesh/mesh_six_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_six_binary"
path = "examples/mesh/mesh_six_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_six_baking"
path = "examples/mesh/mesh_six_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_seven_crossbeam"
path = "examples/mesh/mesh_seven_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_seven_mpst"
path = "examples/mesh/mesh_seven_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_seven_binary"
path = "examples/mesh/mesh_seven_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_seven_baking"
path = "examples/mesh/mesh_seven_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_eight_crossbeam"
path = "examples/mesh/mesh_eight_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eight_mpst"
path = "examples/mesh/mesh_eight_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eight_binary"
path = "examples/mesh/mesh_eight_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eight_baking"
path = "examples/mesh/mesh_eight_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_nine_crossbeam"
path = "examples/mesh/mesh_nine_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_nine_mpst"
path = "examples/mesh/mesh_nine_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_nine_binary"
path = "examples/mesh/mesh_nine_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_nine_baking"
path = "examples/mesh/mesh_nine_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_ten_crossbeam"
path = "examples/mesh/mesh_ten_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_ten_mpst"
path = "examples/mesh/mesh_ten_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_ten_binary"
path = "examples/mesh/mesh_ten_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_ten_baking"
path = "examples/mesh/mesh_ten_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_eleven_crossbeam"
path = "examples/mesh/mesh_eleven_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eleven_mpst"
path = "examples/mesh/mesh_eleven_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eleven_binary"
path = "examples/mesh/mesh_eleven_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_eleven_baking"
path = "examples/mesh/mesh_eleven_baking.rs"
required-features = ["baking"]

[[example]]
name = "mesh_twenty_crossbeam"
path = "examples/mesh/mesh_twenty_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_twenty_mpst"
path = "examples/mesh/mesh_twenty_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_twenty_binary"
path = "examples/mesh/mesh_twenty_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "mesh_twenty_baking"
path = "examples/mesh/mesh_twenty_baking.rs"
required-features = ["baking"]

################################### Ring examples

[[example]]
name = "ring_two_crossbeam"
path = "examples/ring/ring_two_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_two_mpst"
path = "examples/ring/ring_two_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_two_binary"
path = "examples/ring/ring_two_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_two_baking"
path = "examples/ring/ring_two_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_three_crossbeam"
path = "examples/ring/ring_three_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_three_mpst"
path = "examples/ring/ring_three_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_three_binary"
path = "examples/ring/ring_three_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_three_baking"
path = "examples/ring/ring_three_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_four_crossbeam"
path = "examples/ring/ring_four_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_four_mpst"
path = "examples/ring/ring_four_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_four_binary"
path = "examples/ring/ring_four_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_four_baking"
path = "examples/ring/ring_four_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_five_crossbeam"
path = "examples/ring/ring_five_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_five_mpst"
path = "examples/ring/ring_five_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_five_binary"
path = "examples/ring/ring_five_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_five_baking"
path = "examples/ring/ring_five_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_six_crossbeam"
path = "examples/ring/ring_six_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_six_mpst"
path = "examples/ring/ring_six_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_six_binary"
path = "examples/ring/ring_six_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_six_baking"
path = "examples/ring/ring_six_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_seven_crossbeam"
path = "examples/ring/ring_seven_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_seven_mpst"
path = "examples/ring/ring_seven_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_seven_binary"
path = "examples/ring/ring_seven_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_seven_baking"
path = "examples/ring/ring_seven_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_eight_crossbeam"
path = "examples/ring/ring_eight_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eight_mpst"
path = "examples/ring/ring_eight_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eight_binary"
path = "examples/ring/ring_eight_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eight_baking"
path = "examples/ring/ring_eight_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_nine_crossbeam"
path = "examples/ring/ring_nine_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_nine_mpst"
path = "examples/ring/ring_nine_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_nine_binary"
path = "examples/ring/ring_nine_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_nine_baking"
path = "examples/ring/ring_nine_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_ten_crossbeam"
path = "examples/ring/ring_ten_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_ten_mpst"
path = "examples/ring/ring_ten_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_ten_binary"
path = "examples/ring/ring_ten_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_ten_baking"
path = "examples/ring/ring_ten_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_eleven_crossbeam"
path = "examples/ring/ring_eleven_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eleven_mpst"
path = "examples/ring/ring_eleven_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eleven_binary"
path = "examples/ring/ring_eleven_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_eleven_baking"
path = "examples/ring/ring_eleven_baking.rs"
required-features = ["baking"]

[[example]]
name = "ring_twenty_crossbeam"
path = "examples/ring/ring_twenty_crossbeam.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_twenty_mpst"
path = "examples/ring/ring_twenty_mpst.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_twenty_binary"
path = "examples/ring/ring_twenty_binary.rs"
required-features = ["macros_multiple"]

[[example]]
name = "ring_twenty_baking"
path = "examples/ring/ring_twenty_baking.rs"
required-features = ["baking"]

################################### Profil

[profile.release]
debug = true

################################### Dependencies

[dependencies]
mpst-seq = { path = "mpst_seq" }
# mpst-seq = "0.1"
crossbeam-channel = "0.5"
either = "1.6"
hyper = { version = "0.14", features = ["full"], optional = true }
hyper-tls = { version = "0.5", optional = true }
tokio = { version = "1.14", features = ["full"], optional = true }
regex = { version = "1.5", optional = true }
petgraph = { version = "0.6", optional = true }

################################### Dev-dependencies for tests/benches

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
trybuild = "1.0"
ntest = "0.7"
rand = "0.8"

################################### Features

[features]
default = ["binary", "role", "meshedchannels", "functionmpst"]
binary = []
functionmpst = []
meshedchannels = []
role = []
macros_simple = ["default"]
macros_multiple = ["default", "macros_simple"]
# For interleaved sessions
interleaved = ["default"]
checking = ["default", "regex", "petgraph"]
baking = ["default", "macros_multiple"]
baking_interleaved = ["baking", "interleaved"]
baking_checking = ["baking", "checking"]
transport_tcp = ["default"]
transport_udp = ["default"]
transport_http = ["default", "hyper", "hyper-tls", "tokio"]
transport = ["transport_tcp", "transport_udp", "transport_http"]
# For test compile examples
transport_macros_multiple = ["macros_multiple", "transport"]
full = ["checking", "baking", "transport"]

################################### Doc handling for all-features

# docs.rs-specific configuration
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

################################### Rust playground features

[package.metadata.playground]
features = ["full", "interleaved"]
