use criterion::criterion_main;

mod benchmarks;

criterion_main! {
    benchmarks::long_five::long_five_protocols,
    benchmarks::mesh::mesh_three_empty::long_three_empty_simple_protocols,
    benchmarks::mesh::mesh_three::mesh_three_protocol,
    benchmarks::mesh::mesh_cancel_three::mesh_three_protocol,
    benchmarks::mesh::mesh_three_short::mesh_three_protocol_short,
    benchmarks::mesh::mesh_four_empty::long_four_empty_simple_protocols,
    benchmarks::mesh::mesh_four::mesh_four_protocol,
    benchmarks::mesh::mesh_cancel_four::mesh_four_protocol,
    benchmarks::mesh::mesh_five_empty::long_five_empty_simple_protocols,
    benchmarks::mesh::mesh_five::mesh_five_protocol,
    benchmarks::mesh::mesh_cancel_five::mesh_five_protocol,
    benchmarks::mesh::mesh_six_empty::long_six_empty_simple_protocols,
    benchmarks::mesh::mesh_six::mesh_six_protocol,
    benchmarks::mesh::mesh_cancel_six::mesh_six_protocol,
    benchmarks::mesh::mesh_seven_empty::long_seven_empty_simple_protocols,
    benchmarks::mesh::mesh_seven::mesh_seven_protocol,
    benchmarks::mesh::mesh_cancel_seven::mesh_seven_protocol,
    benchmarks::mesh::mesh_eight_empty::long_eight_empty_simple_protocols,
    benchmarks::mesh::mesh_eight::mesh_eight_protocol,
    benchmarks::mesh::mesh_cancel_eight::mesh_eight_protocol,
    benchmarks::mesh::mesh_nine_empty::long_nine_empty_simple_protocols,
    benchmarks::mesh::mesh_nine::mesh_nine_protocol,
    benchmarks::mesh::mesh_cancel_nine::mesh_nine_protocol,
    benchmarks::mesh::mesh_ten_empty::long_ten_empty_simple_protocols,
    benchmarks::mesh::mesh_ten::mesh_ten_protocol,
    benchmarks::mesh::mesh_cancel_ten::mesh_ten_protocol,
    benchmarks::mesh::mesh_eleven_empty::long_eleven_empty_simple_protocols,
    benchmarks::mesh::mesh_eleven::mesh_eleven_protocol,
    benchmarks::mesh::mesh_cancel_eleven::mesh_eleven_protocol,
    benchmarks::mesh::mesh_twenty_empty::long_twenty_empty_simple_protocols,
    benchmarks::mesh::mesh_twenty::mesh_twenty_protocol,
    benchmarks::mesh::mesh_cancel_twenty::mesh_twenty_protocol,
    //////////
    benchmarks::fib::fibo,
    benchmarks::o_auth::o_auth,
    benchmarks::simple_voting_three::simple_voting,
    benchmarks::travel_three::travel,
    benchmarks::three_buyer::three_buyer,
    benchmarks::ping_pong::ping_pong,
    //////////
    benchmarks::ring::ring_three::ring_three,
    benchmarks::ring::ring_four::ring_four,
    benchmarks::ring::ring_five::ring_five,
    benchmarks::ring::ring_six::ring_six,
    benchmarks::ring::ring_seven::ring_seven,
    benchmarks::ring::ring_eight::ring_eight,
}
