use criterion::criterion_main;

mod benchmarks;

criterion_main! {
    // //////////
    // benchmarks::mesh::mesh_three_short::mesh_three_short,
    // //////////
    benchmarks::mesh::empty::mesh_three_empty::mesh_three_empty,
    benchmarks::mesh::empty::mesh_four_empty::mesh_four_empty,
    benchmarks::mesh::empty::mesh_five_empty::mesh_five_empty,
    benchmarks::mesh::empty::mesh_six_empty::mesh_six_empty,
    benchmarks::mesh::empty::mesh_seven_empty::mesh_seven_empty,
    benchmarks::mesh::empty::mesh_eight_empty::mesh_eight_empty,
    benchmarks::mesh::empty::mesh_nine_empty::mesh_nine_empty,
    benchmarks::mesh::empty::mesh_ten_empty::mesh_ten_empty,
    benchmarks::mesh::empty::mesh_eleven_empty::mesh_eleven_empty,
    benchmarks::mesh::empty::mesh_twenty_empty::mesh_twenty_empty,
    //////////
    benchmarks::mesh::normal::mesh_three::mesh_three,
    benchmarks::mesh::normal::mesh_four::mesh_four,
    benchmarks::mesh::normal::mesh_five::mesh_five,
    benchmarks::mesh::normal::mesh_six::mesh_six,
    benchmarks::mesh::normal::mesh_seven::mesh_seven,
    benchmarks::mesh::normal::mesh_eight::mesh_eight,
    benchmarks::mesh::normal::mesh_nine::mesh_nine,
    benchmarks::mesh::normal::mesh_ten::mesh_ten,
    benchmarks::mesh::normal::mesh_eleven::mesh_eleven,
    benchmarks::mesh::normal::mesh_twenty::mesh_twenty,
    //////////
    benchmarks::mesh::cancel::mesh_three_cancel::mesh_three,
    benchmarks::mesh::cancel::mesh_four_cancel::mesh_four,
    benchmarks::mesh::cancel::mesh_five_cancel::mesh_five,
    benchmarks::mesh::cancel::mesh_six_cancel::mesh_six,
    benchmarks::mesh::cancel::mesh_seven_cancel::mesh_seven,
    benchmarks::mesh::cancel::mesh_eight_cancel::mesh_eight,
    benchmarks::mesh::cancel::mesh_nine_cancel::mesh_nine,
    benchmarks::mesh::cancel::mesh_ten_cancel::mesh_ten,
    benchmarks::mesh::cancel::mesh_eleven_cancel::mesh_eleven,
    benchmarks::mesh::cancel::mesh_twenty_cancel::mesh_twenty,
    // //////////
    // benchmarks::basic::choose_five::choose_five,
    benchmarks::basic::long_five::long_five_protocol,
    // benchmarks::basic::actyx_os_1::actyx_os_1,
    // benchmarks::basic::actyx_os_2::actyx_os_2,
    // benchmarks::basic::distributed_calc::distributed_calc,
    // benchmarks::basic::fib::fib,
    // benchmarks::basic::o_auth::o_auth,
    // benchmarks::basic::online_wallet::online_wallet,
    // benchmarks::basic::ping_pong::ping_pong,
    // benchmarks::basic::simple_voting_three::simple_voting,
    // benchmarks::basic::smtp::smtp,
    // benchmarks::basic::three_buyer::three_buyer,
    // benchmarks::basic::travel_three::travel_three,
    // benchmarks::basic::video_stream::video_stream,
    // //////////
    benchmarks::ring::empty::ring_three_empty::ring_three,
    benchmarks::ring::empty::ring_four_empty::ring_four,
    benchmarks::ring::empty::ring_five_empty::ring_five,
    benchmarks::ring::empty::ring_six_empty::ring_six,
    benchmarks::ring::empty::ring_seven_empty::ring_seven,
    benchmarks::ring::empty::ring_eight_empty::ring_eight,
    benchmarks::ring::empty::ring_nine_empty::ring_nine,
    benchmarks::ring::empty::ring_ten_empty::ring_ten,
    benchmarks::ring::empty::ring_eleven_empty::ring_eleven,
    benchmarks::ring::empty::ring_twenty_empty::ring_twenty,
    //////////
    benchmarks::ring::normal::ring_three::ring_three,
    benchmarks::ring::normal::ring_four::ring_four,
    benchmarks::ring::normal::ring_five::ring_five,
    benchmarks::ring::normal::ring_six::ring_six,
    benchmarks::ring::normal::ring_seven::ring_seven,
    benchmarks::ring::normal::ring_eight::ring_eight,
    benchmarks::ring::normal::ring_nine::ring_nine,
    benchmarks::ring::normal::ring_ten::ring_ten,
    benchmarks::ring::normal::ring_eleven::ring_eleven,
    benchmarks::ring::normal::ring_twenty::ring_twenty,
    //////////
    benchmarks::ring::cancel::ring_three_cancel::ring_three,
    benchmarks::ring::cancel::ring_four_cancel::ring_four,
    benchmarks::ring::cancel::ring_five_cancel::ring_five,
    benchmarks::ring::cancel::ring_six_cancel::ring_six,
    benchmarks::ring::cancel::ring_seven_cancel::ring_seven,
    benchmarks::ring::cancel::ring_eight_cancel::ring_eight,
    benchmarks::ring::cancel::ring_nine_cancel::ring_nine,
    benchmarks::ring::cancel::ring_ten_cancel::ring_ten,
    benchmarks::ring::cancel::ring_eleven_cancel::ring_eleven,
    benchmarks::ring::cancel::ring_twenty_cancel::ring_twenty,
}
