#![allow(dead_code, clippy::type_complexity, clippy::too_many_arguments)]

use criterion::{criterion_group, criterion_main, Criterion};

mod mesh_all;

criterion_group! {
    name = mesh_full;
    config = Criterion::default().significance_level(0.1).sample_size(10000);
    targets =
        ////////// Benchmarks using basic functions with zero loops
        mesh_all::empty::mesh_two_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_two_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_two_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_three_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_three_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_three_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_four_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_four_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_four_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_five_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_five_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_five_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_six_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_six_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_six_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_seven_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_seven_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_seven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_eight_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_eight_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_eight_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_nine_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_nine_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_nine_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_ten_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_ten_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_ten_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_eleven_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_eleven_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_eleven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::empty::mesh_twenty_mpst::mesh_protocol_mpst,
        mesh_all::empty::mesh_twenty_binary::mesh_protocol_binary,
        mesh_all::empty::mesh_twenty_crossbeam::mesh_protocol_crossbeam,
        ////////// Benchmarks using basic functions with 100 loops
        mesh_all::normal::mesh_two_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_two_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_two_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_three_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_three_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_three_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_four_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_four_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_four_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_five_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_five_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_five_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_six_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_six_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_six_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_seven_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_seven_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_seven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_eight_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_eight_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_eight_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_nine_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_nine_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_nine_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_ten_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_ten_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_ten_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_eleven_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_eleven_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_eleven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::normal::mesh_twenty_mpst::mesh_protocol_mpst,
        mesh_all::normal::mesh_twenty_binary::mesh_protocol_binary,
        mesh_all::normal::mesh_twenty_crossbeam::mesh_protocol_crossbeam,
        ////////// Benchmarks using cancelling with a monitor to broadcast cancel with 100 loops
        mesh_all::cancel_broadcast::mesh_three::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_four::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_five::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_six::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_seven::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_eight::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_nine::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_ten::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_eleven::mesh_protocol_mpst,
        mesh_all::cancel_broadcast::mesh_twenty::mesh_protocol_mpst,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using basic functions with 100 loops
        mesh_all::cancel::mesh_two_mpst::mesh_protocol,
        mesh_all::cancel::mesh_three_mpst::mesh_protocol,
        mesh_all::cancel::mesh_four_mpst::mesh_protocol,
        mesh_all::cancel::mesh_five_mpst::mesh_protocol,
        mesh_all::cancel::mesh_six_mpst::mesh_protocol,
        mesh_all::cancel::mesh_seven_mpst::mesh_protocol,
        mesh_all::cancel::mesh_eight_mpst::mesh_protocol,
        mesh_all::cancel::mesh_nine_mpst::mesh_protocol,
        mesh_all::cancel::mesh_ten_mpst::mesh_protocol,
        mesh_all::cancel::mesh_eleven_mpst::mesh_protocol,
        mesh_all::cancel::mesh_twenty_mpst::mesh_protocol,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using generated methods with 100 loops
        mesh_all::baking::mesh_two_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_two_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_two_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_two_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_three_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_three_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_three_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_three_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_four_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_four_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_four_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_four_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_five_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_five_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_five_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_five_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_six_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_six_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_six_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_six_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_seven_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_seven_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_seven_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_seven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_eight_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_eight_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_eight_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_eight_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_nine_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_nine_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_nine_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_nine_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_ten_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_ten_ampst_ampst::mesh_protocol_ampst,
        mesh_all::baking::mesh_ten_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_ten_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_eleven_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_eleven_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_eleven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking::mesh_twenty_mpst::mesh_protocol_mpst,
        mesh_all::baking::mesh_twenty_binary::mesh_protocol_binary,
        mesh_all::baking::mesh_twenty_crossbeam::mesh_protocol_crossbeam,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using generated methods with inline compilation with 100 loops
        mesh_all::baking_cancel_inline::mesh_two_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_two_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_two_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_three_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_three_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_three_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_four_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_four_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_four_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_five_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_five_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_five_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_six_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_six_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_six_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_seven_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_seven_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_seven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_eight_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_eight_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_eight_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_nine_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_nine_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_nine_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_ten_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_ten_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_ten_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_eleven_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_eleven_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_eleven_crossbeam::mesh_protocol_crossbeam,
        mesh_all::baking_cancel_inline::mesh_twenty_mpst::mesh_protocol,
        mesh_all::baking_cancel_inline::mesh_twenty_binary::mesh_protocol_binary,
        mesh_all::baking_cancel_inline::mesh_twenty_crossbeam::mesh_protocol_crossbeam,
        ////////// Benchmarks using timed cancelling without a monitor to broadcast cancel using generated methods with 100 loops
        mesh_all::timed_baking_cancel::mesh_two::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_three::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_four::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_five::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_six::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_seven::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_eight::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_nine::mesh_protocol_mpst,
        mesh_all::timed_baking_cancel::mesh_ten::mesh_protocol_mpst,
}

criterion_main! {
    mesh_full
}
