#![allow(dead_code, clippy::type_complexity, clippy::too_many_arguments)]

use criterion::{criterion_group, criterion_main, Criterion};

mod ring_all;

criterion_group! {
    name = ring_full;
    config = Criterion::default().significance_level(0.1).sample_size(10000);
    targets =
        ////////// Benchmarks using basic functions with zero loops
        ring_all::empty::ring_two_mpst::ring_protocol_mpst,
        ring_all::empty::ring_two_binary::ring_protocol_binary,
        ring_all::empty::ring_two_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_three_mpst::ring_protocol_mpst,
        ring_all::empty::ring_three_binary::ring_protocol_binary,
        ring_all::empty::ring_three_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_four_mpst::ring_protocol_mpst,
        ring_all::empty::ring_four_binary::ring_protocol_binary,
        ring_all::empty::ring_four_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_five_mpst::ring_protocol_mpst,
        ring_all::empty::ring_five_binary::ring_protocol_binary,
        ring_all::empty::ring_five_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_six_mpst::ring_protocol_mpst,
        ring_all::empty::ring_six_binary::ring_protocol_binary,
        ring_all::empty::ring_six_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_seven_mpst::ring_protocol_mpst,
        ring_all::empty::ring_seven_binary::ring_protocol_binary,
        ring_all::empty::ring_seven_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_eight_mpst::ring_protocol_mpst,
        ring_all::empty::ring_eight_binary::ring_protocol_binary,
        ring_all::empty::ring_eight_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_nine_mpst::ring_protocol_mpst,
        ring_all::empty::ring_nine_binary::ring_protocol_binary,
        ring_all::empty::ring_nine_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_ten_mpst::ring_protocol_mpst,
        ring_all::empty::ring_ten_binary::ring_protocol_binary,
        ring_all::empty::ring_ten_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_eleven_mpst::ring_protocol_mpst,
        ring_all::empty::ring_eleven_binary::ring_protocol_binary,
        ring_all::empty::ring_eleven_crossbeam::ring_protocol_crossbeam,
        ring_all::empty::ring_twenty_mpst::ring_protocol_mpst,
        ring_all::empty::ring_twenty_binary::ring_protocol_binary,
        ring_all::empty::ring_twenty_crossbeam::ring_protocol_crossbeam,
        ////////// Benchmarks using basic functions with 100 loops
        ring_all::normal::ring_two_mpst::ring_protocol_mpst,
        ring_all::normal::ring_two_binary::ring_protocol_binary,
        ring_all::normal::ring_two_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_three_mpst::ring_protocol_mpst,
        ring_all::normal::ring_three_binary::ring_protocol_binary,
        ring_all::normal::ring_three_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_four_mpst::ring_protocol_mpst,
        ring_all::normal::ring_four_binary::ring_protocol_binary,
        ring_all::normal::ring_four_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_five_mpst::ring_protocol_mpst,
        ring_all::normal::ring_five_binary::ring_protocol_binary,
        ring_all::normal::ring_five_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_six_mpst::ring_protocol_mpst,
        ring_all::normal::ring_six_binary::ring_protocol_binary,
        ring_all::normal::ring_six_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_seven_mpst::ring_protocol_mpst,
        ring_all::normal::ring_seven_binary::ring_protocol_binary,
        ring_all::normal::ring_seven_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_eight_mpst::ring_protocol_mpst,
        ring_all::normal::ring_eight_binary::ring_protocol_binary,
        ring_all::normal::ring_eight_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_nine_mpst::ring_protocol_mpst,
        ring_all::normal::ring_nine_binary::ring_protocol_binary,
        ring_all::normal::ring_nine_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_ten_mpst::ring_protocol_mpst,
        ring_all::normal::ring_ten_binary::ring_protocol_binary,
        ring_all::normal::ring_ten_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_eleven_mpst::ring_protocol_mpst,
        ring_all::normal::ring_eleven_binary::ring_protocol_binary,
        ring_all::normal::ring_eleven_crossbeam::ring_protocol_crossbeam,
        ring_all::normal::ring_twenty_mpst::ring_protocol_mpst,
        ring_all::normal::ring_twenty_binary::ring_protocol_binary,
        ring_all::normal::ring_twenty_crossbeam::ring_protocol_crossbeam,
        ////////// Benchmarks using cancelling with a monitor to broadcast cancel with 100 loops
        ring_all::cancel_broadcast::ring_three::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_four::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_five::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_six::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_seven::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_eight::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_nine::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_ten::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_eleven::ring_protocol_mpst,
        ring_all::cancel_broadcast::ring_twenty::ring_protocol_mpst,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using basic functions with 100 loops
        ring_all::cancel::ring_two_mpst::ring_protocol,
        ring_all::cancel::ring_three_mpst::ring_protocol,
        ring_all::cancel::ring_four_mpst::ring_protocol,
        ring_all::cancel::ring_five_mpst::ring_protocol,
        ring_all::cancel::ring_six_mpst::ring_protocol,
        ring_all::cancel::ring_seven_mpst::ring_protocol,
        ring_all::cancel::ring_eight_mpst::ring_protocol,
        ring_all::cancel::ring_nine_mpst::ring_protocol,
        ring_all::cancel::ring_ten_mpst::ring_protocol,
        ring_all::cancel::ring_eleven_mpst::ring_protocol,
        ring_all::cancel::ring_twenty_mpst::ring_protocol,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using generated methods with 100 loops
        ring_all::baking::ring_two_mpst::ring_protocol_mpst,
        ring_all::baking::ring_two_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_two_binary::ring_protocol_binary,
        ring_all::baking::ring_two_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_three_mpst::ring_protocol_mpst,
        ring_all::baking::ring_three_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_three_binary::ring_protocol_binary,
        ring_all::baking::ring_three_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_four_mpst::ring_protocol_mpst,
        ring_all::baking::ring_four_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_four_binary::ring_protocol_binary,
        ring_all::baking::ring_four_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_five_mpst::ring_protocol_mpst,
        ring_all::baking::ring_five_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_five_binary::ring_protocol_binary,
        ring_all::baking::ring_five_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_six_mpst::ring_protocol_mpst,
        ring_all::baking::ring_six_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_six_binary::ring_protocol_binary,
        ring_all::baking::ring_six_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_seven_mpst::ring_protocol_mpst,
        ring_all::baking::ring_seven_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_seven_binary::ring_protocol_binary,
        ring_all::baking::ring_seven_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_eight_mpst::ring_protocol_mpst,
        ring_all::baking::ring_eight_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_eight_binary::ring_protocol_binary,
        ring_all::baking::ring_eight_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_nine_mpst::ring_protocol_mpst,
        ring_all::baking::ring_nine_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_nine_binary::ring_protocol_binary,
        ring_all::baking::ring_nine_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_ten_mpst::ring_protocol_mpst,
        ring_all::baking::ring_ten_ampst_ampst::ring_protocol_ampst,
        ring_all::baking::ring_ten_binary::ring_protocol_binary,
        ring_all::baking::ring_ten_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_eleven_mpst::ring_protocol_mpst,
        ring_all::baking::ring_eleven_binary::ring_protocol_binary,
        ring_all::baking::ring_eleven_crossbeam::ring_protocol_crossbeam,
        ring_all::baking::ring_twenty_mpst::ring_protocol_mpst,
        ring_all::baking::ring_twenty_binary::ring_protocol_binary,
        ring_all::baking::ring_twenty_crossbeam::ring_protocol_crossbeam,
        ////////// Benchmarks using cancelling without a monitor to broadcast cancel using generated methods with inline compilation with 100 loops
        ring_all::baking_cancel_inline::ring_two_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_two_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_two_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_three_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_three_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_three_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_four_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_four_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_four_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_five_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_five_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_five_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_six_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_six_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_six_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_seven_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_seven_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_seven_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_eight_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_eight_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_eight_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_nine_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_nine_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_nine_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_ten_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_ten_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_ten_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_eleven_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_eleven_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_eleven_crossbeam::ring_protocol_crossbeam,
        ring_all::baking_cancel_inline::ring_twenty_mpst::ring_protocol,
        ring_all::baking_cancel_inline::ring_twenty_binary::ring_protocol_binary,
        ring_all::baking_cancel_inline::ring_twenty_crossbeam::ring_protocol_crossbeam,
        ////////// Benchmarks using timed cancelling without a monitor to broadcast cancel using generated methods with 100 loops
        ring_all::timed_baking_cancel::ring_two::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_three::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_four::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_five::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_six::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_seven::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_eight::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_nine::ring_protocol_mpst,
        ring_all::timed_baking_cancel::ring_ten::ring_protocol_mpst,
}

criterion_main! {
    ring_full
}
