name: Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml --timeout 900
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN -F unittests