name: Mac

on: [push, pull_request]

jobs:
  mac-build:
    name: Build, test and benchmarks all on MacOS

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2
    # - name: Install Haskell
    #   uses: actions/setup-haskell@v1.1
    #   with:
    #     ghc-version: 'latest'
    #     cabal-version: 'latest'
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 'latest'
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install matplotlib scipy
    # - name: Install cabal dependencies
    #   run: |
    #     cabal install cmdargs ansi-terminal parallel split MissingH --lib
    # - name: Install KMC
    #   run: |
    #     cd ..
    #     git clone https://bitbucket.org/julien-lange/kmc-cav19.git
    #     cd kmc-cav19
    #     ghc KMC -threaded
    #     ghc GenCFSMs
    - name: Format
      run: cargo fmt --verbose --all -- --check
    - name: Clippy
      run: cargo clippy --all-features --verbose -- -D warnings
    - name: Check lib
      run: cargo check --verbose --all --all-features
    - name: Check examples
      run: cargo check --examples --verbose --all-features
    - name: Check tests
      run: cargo check --tests --verbose --all-features
    - name: Check benches
      run: cargo check --benches --verbose --all-features
    - name: Run doc
      run: cargo doc --verbose --workspace --all-features
    - name: Build lib
      run: cargo build --verbose --all --all-features
    - name: Build examples
      run: cargo build --examples --verbose --all-features
    - name: Build tests
      run: cargo build --tests --verbose --all-features
    - name: Build benches
      run: cargo build --benches --verbose --all-features
    - name: Run lib
      run: cargo run --verbose --all-features -- --skip kmc
    - name: Run tests all
      run: cargo test --verbose --all -- --skip kmc
    - name: Run tests no capture
      run: cargo test --verbose --all -- --nocapture --skip kmc
    - name: Run tests no features
      run: cargo test --verbose --all --no-default-features --no-run -- --skip kmc
    - name: Run tests all features
      run: cargo test --verbose --all-features -- --skip kmc
    - name: Run benchmarks
      run: cargo bench --verbose --all
