name: Rust

on: [push]

jobs:
  build:
    name: Build, test and benchmarks all

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --verbose 
    - name: Build
      run: cargo build --verbose --all
    - name: Check
      run: cargo check --verbose --all
    - name: Run tests all
      run: cargo test --verbose --all
    - name: Run tests no capture
      run: cargo test --verbose -- --nocapture
    - name: Run tests no features
      run: cargo test --verbose --no-default-features --no-run
    - name: Run examples
      run: find ./examples/. -type f -exec sh -c 'for example in "$@"; do (cargo run --example ${example:13:-3}) done' argv0 {} +
    - name: Run benchmarks
      run: cargo bench --verbose --all
    - name: Run doc
      run: cargo doc --verbose --all
