name: Ubuntu

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Build, test and benchmarks all on Ubuntu

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, 1.71, 1.72]

    steps:
    - uses: actions/checkout@v3
    # - name: Install Haskell
    #   uses: actions/setup-haskell@v1.1
    #   with:
    #     ghc-version: 'latest'
    #     cabal-version: 'latest'
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 'latest'
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install matplotlib scipy
    # - name: Install cabal dependencies
    #   run: |
    #     cabal install cmdargs ansi-terminal parallel split MissingH --lib
    # - name: Install KMC
    #   run: |
    #     cd ..
    #     git clone https://bitbucket.org/julien-lange/kmc-cav19.git
    #     cd kmc-cav19
    #     ghc KMC -threaded
    #     ghc GenCFSMs
    - name: Check Rust version
      run: rustup --version
    - name: Format
      run: cargo fmt --verbose --all -- --check
    - name: Clippy
      run: cargo clippy --workspace --all-features --all-targets --verbose -- -D warnings
    - name: Build lib
      run: cargo build --verbose --workspace --all-features
    - name: Test all targets but skip kmc and transport_udp
      run: |
        cargo test --verbose --all-targets --workspace --no-default-features -- --skip kmc --skip transport_udp
        cargo test --verbose --all-targets --workspace -- --skip kmc --skip transport_udp
        cargo test --verbose --all-targets --workspace --all-features -- --skip kmc --skip transport_udp
