name: Ubuntu

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Build, test and benchmarks all on Ubuntu

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, 1.70.0, 1.69.0, 1.68.0]

    steps:
    - uses: actions/checkout@v2
    # - name: Install Haskell
    #   uses: actions/setup-haskell@v1.1
    #   with:
    #     ghc-version: 'latest'
    #     cabal-version: 'latest'
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 'latest'
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install matplotlib scipy
    # - name: Install cabal dependencies
    #   run: |
    #     cabal install cmdargs ansi-terminal parallel split MissingH --lib
    # - name: Install KMC
    #   run: |
    #     cd ..
    #     git clone https://bitbucket.org/julien-lange/kmc-cav19.git
    #     cd kmc-cav19
    #     ghc KMC -threaded
    #     ghc GenCFSMs
    - name: Format
      run: |
        cargo fmt --verbose --all -- --check
    - name: Clippy
      run: |
        cargo clippy --workspace --all-features --all-targets --verbose -- -D warnings
    - name: Check lib
      run: |
        cargo build --verbose --workspace --all-features
    - name: Check bins
      run: |
        cargo check --bins --verbose --workspace --features="default"
        cargo check --bins --verbose --workspace --features="macros_simple"
        cargo check --bins --verbose --workspace --features="macros_multiple"
        cargo check --bins --verbose --workspace --features="interleaved"
        cargo check --bins --verbose --workspace --features="checking"
        cargo check --bins --verbose --workspace --features="macros_multiple checking"
        cargo check --bins --verbose --workspace --features="baking"
        cargo check --bins --verbose --workspace --features="baking_timed"
        cargo check --bins --verbose --workspace --features="baking_interleaved"
        cargo check --bins --verbose --workspace --features="baking_timed_interleaved"
        cargo check --bins --verbose --workspace --features="baking_checking"
        cargo check --bins --verbose --workspace --features="transport_tcp"
        cargo check --bins --verbose --workspace --features="transport_udp"
        cargo check --bins --verbose --workspace --features="transport_http"
        cargo check --bins --verbose --workspace --features="transport"
        cargo check --bins --verbose --workspace --features="transport_macros_multiple"
        cargo check --bins --verbose --workspace --features="affine_timed"
        cargo check --bins --verbose --workspace --features="full_without_checking"
        cargo check --bins --verbose --workspace --features="full"
        cargo check --bins --verbose --workspace --all-features
    - name: Check tests
      run: |
        cargo check --tests --verbose --workspace --features="default"
        cargo check --tests --verbose --workspace --features="macros_simple"
        cargo check --tests --verbose --workspace --features="macros_multiple"
        cargo check --tests --verbose --workspace --features="interleaved"
        cargo check --tests --verbose --workspace --features="checking"
        cargo check --tests --verbose --workspace --features="macros_multiple checking"
        cargo check --tests --verbose --workspace --features="baking"
        cargo check --tests --verbose --workspace --features="baking_timed"
        cargo check --tests --verbose --workspace --features="baking_interleaved"
        cargo check --tests --verbose --workspace --features="baking_timed_interleaved"
        cargo check --tests --verbose --workspace --features="baking_checking"
        cargo check --tests --verbose --workspace --features="transport_tcp"
        cargo check --tests --verbose --workspace --features="transport_udp"
        cargo check --tests --verbose --workspace --features="transport_http"
        cargo check --tests --verbose --workspace --features="transport"
        cargo check --tests --verbose --workspace --features="transport_macros_multiple"
        cargo check --tests --verbose --workspace --features="affine_timed"
        cargo check --tests --verbose --workspace --features="full_without_checking"
        cargo check --tests --verbose --workspace --features="full"
        cargo check --tests --verbose --workspace --all-features
    - name: Check examples
      run: |
        cargo check --examples --verbose --workspace --features="default"
        cargo check --examples --verbose --workspace --features="macros_simple"
        cargo check --examples --verbose --workspace --features="macros_multiple"
        cargo check --examples --verbose --workspace --features="interleaved"
        cargo check --examples --verbose --workspace --features="checking"
        cargo check --examples --verbose --workspace --features="macros_multiple checking"
        cargo check --examples --verbose --workspace --features="baking"
        cargo check --examples --verbose --workspace --features="baking_timed"
        cargo check --examples --verbose --workspace --features="baking_interleaved"
        cargo check --examples --verbose --workspace --features="baking_timed_interleaved"
        cargo check --examples --verbose --workspace --features="baking_checking"
        cargo check --examples --verbose --workspace --features="transport_tcp"
        cargo check --examples --verbose --workspace --features="transport_udp"
        cargo check --examples --verbose --workspace --features="transport_http"
        cargo check --examples --verbose --workspace --features="transport"
        cargo check --examples --verbose --workspace --features="transport_macros_multiple"
        cargo check --examples --verbose --workspace --features="affine_timed"
        cargo check --examples --verbose --workspace --features="full_without_checking"
        cargo check --examples --verbose --workspace --features="full"
        cargo check --examples --verbose --workspace --all-features
    - name: Check benches
      run: |
        cargo check --benches --verbose --workspace --features="default"
        cargo check --benches --verbose --workspace --features="macros_simple"
        cargo check --benches --verbose --workspace --features="macros_multiple"
        cargo check --benches --verbose --workspace --features="interleaved"
        cargo check --benches --verbose --workspace --features="checking"
        cargo check --benches --verbose --workspace --features="macros_multiple checking"
        cargo check --benches --verbose --workspace --features="baking"
        cargo check --benches --verbose --workspace --features="baking_timed"
        cargo check --benches --verbose --workspace --features="baking_interleaved"
        cargo check --benches --verbose --workspace --features="baking_timed_interleaved"
        cargo check --benches --verbose --workspace --features="baking_checking"
        cargo check --benches --verbose --workspace --features="transport_tcp"
        cargo check --benches --verbose --workspace --features="transport_udp"
        cargo check --benches --verbose --workspace --features="transport_http"
        cargo check --benches --verbose --workspace --features="transport"
        cargo check --benches --verbose --workspace --features="transport_macros_multiple"
        cargo check --benches --verbose --workspace --features="affine_timed"
        cargo check --benches --verbose --workspace --features="full_without_checking"
        cargo check --benches --verbose --workspace --features="full"
        cargo check --benches --verbose --workspace --all-features
    - name: Run doc
      run: |
        cargo doc --verbose --workspace --all-features
    - name: Run lib
      run: |
        cargo run --verbose --all-features
    - name: Run tests all
      run: |
        cargo test --verbose --lib --workspace -- --skip kmc --skip transport_udp
        cargo test --verbose --bins --workspace -- --skip kmc --skip transport_udp
        cargo test --verbose --tests --workspace -- --skip kmc --skip transport_udp
        cargo test --verbose --examples --workspace -- --skip kmc --skip transport_udp
        cargo test --verbose --benches --workspace -- --skip kmc --skip transport_udp
        # cargo test --verbose --all-targets --workspace -- --skip kmc --skip transport_udp
    - name: Run tests no capture
      run: |
        cargo test --verbose --lib --workspace -- --nocapture --skip kmc --skip transport_udp
        cargo test --verbose --bins --workspace -- --nocapture --skip kmc --skip transport_udp
        cargo test --verbose --tests --workspace -- --nocapture --skip kmc --skip transport_udp
        cargo test --verbose --examples --workspace -- --nocapture --skip kmc --skip transport_udp
        cargo test --verbose --benches --workspace -- --nocapture --skip kmc --skip transport_udp
        # cargo test --verbose --all-targets --workspace -- --nocapture --skip kmc --skip transport_udp
    - name: Run tests no features
      run: |
        cargo test --verbose --lib --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
        cargo test --verbose --bins --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
        cargo test --verbose --tests --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
        cargo test --verbose --examples --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
        cargo test --verbose --benches --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
        # cargo test --verbose --all-targets --workspace --no-default-features --no-run -- --skip kmc --skip transport_udp
    - name: Run tests all features
      run: |
        cargo test --verbose --lib --workspace --all-features -- --skip kmc --skip transport_udp
        cargo test --verbose --bins --workspace --all-features -- --skip kmc --skip transport_udp
        cargo test --verbose --tests --workspace --all-features -- --skip kmc --skip transport_udp
        cargo test --verbose --examples --workspace --all-features -- --skip kmc --skip transport_udp
        cargo test --verbose --benches --workspace --all-features
    # - name: Run benchmarks
    #   run: |
    #     cargo bench --verbose --all-targets --workspace --all-features
    # - name: Run examples
    #   run: |
    #     cargo run --example circuit_breaker --features="macros_multiple"
    #     cargo run --example logging --features="macros_multiple"
    #     cargo run --example circuit_breaker_baking --features="baking"
    #     cargo run --example logging_baking --features="baking"
    #     cargo run --example circuit_breaker_solo --features="baking_interleaved"
    #     cargo run --example logging_solo --features="baking_interleaved"
    #     cargo run --example circuit_breaker_logging_interleaved --features="baking_interleaved"
    #     cargo run --example calculator --features="macros_multiple"
    #     cargo run --example dns_fowler --features="baking"
    #     cargo run --example dns_imai --features="macros_multiple"
    #     cargo run --example fib --features="macros_multiple"
    #     cargo run --example o_auth --features="baking"
    #     cargo run --example o_auth_transport --features="transport_macros_multiple"
    #     cargo run --example online_wallet --features="macros_multiple"
    #     cargo run --example simple_voting --features="macros_multiple"
    #     cargo run --example smtp --features="macros_multiple"
    #     cargo run --example three_buyers --features="macros_multiple"
    #     cargo run --example travel_agency --features="macros_multiple"
    #     cargo run --example video_stream --features="macros_simple"
