[package]
name = "mpst-seq-proc"
version = "0.0.1"
edition = "2018"
autotests = false

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.73", features = ["extra-traits", "full", "parsing"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
proc-macro-hack = "0.5.19"
